"use strict";var DESKTOP_MQ="(min-width: 900px)",PARALLAX_SUPPORTED=CSS.supports("transform-style","preserve-3d"),IObserverReady=new Promise(function(a){if("IntersectionObserver"in window)a();else{var b=document.createElement("script");b.src="https://polyfill.io/v2/polyfill.min.js?features=IntersectionObserver",b.onload=a,document.head.appendChild(b)}});// Ensure we have Intersection Observer, otherwise load a polyfill
window.AppState={parallaxEnabled:!1,/**
   * Currently opened overlay element,
   * clicking it should close the overlay
   * @type {?Element}
   */openedOverlay:null};function doubleRAF(a){requestAnimationFrame(function(){requestAnimationFrame(a)})}function waitForTransition(a,b){return new Promise(function(c){a.addEventListener("transitionend",function d(f){(b||f.target===a)&&(c(),a.removeEventListener("transitionend",d))})})}// Load our lazy CSS
// Fix 'more info' sections after parallax is added
// Load parallax images
// Mark sections as active
// Passively listen for scroll to add waterfall effect
// Close navigation drawer on click outside (mobile)
// Handle back navigation
// // Add phone parallax effect if supported
(function(){var a=document.querySelector("#lazyload-css");a.insertAdjacentHTML("afterend",a.textContent)})(),function(){var a=document.querySelectorAll("section .text-container");a.forEach(function(a){var b=a.querySelector(".expandable"),c=a.querySelector(".text-toggle");c.addEventListener("change",function(){var a=c.checked;if(a){var d=b.closest("section").id;// Add entry to history so we can close this on back navigation
window.AppState.openedOverlay=b,history.pushState({},document.title,"?section=".concat(d)),b.setAttribute("data-section",d),b.addEventListener("click",function a(d){d.target===b&&(window.AppState.openedOverlay&&(window.AppState.openedOverlay=null,history.back()),c.click(),b.removeEventListener("click",a,{passive:!0}),waitForTransition(b,!0).then(function(){var a=b.getAttribute("data-section");document.querySelector("#".concat(a," .text-container")).appendChild(b),document.body.style.overflow="",b.style.transform=""}),b.classList.remove("open"))},{passive:!0}),document.body.style.overflow="hidden",window.AppState.parallaxEnabled&&(b.style.transform="translateY(".concat(document.body.scrollTop,"px)")),b.classList.add("upgraded"),document.body.appendChild(b),doubleRAF(function(){return b.classList.add("open")})}})})}(),function(){function a(){PARALLAX_SUPPORTED&&window.matchMedia(DESKTOP_MQ).matches?(document.body.classList.add("upgraded-parallax"),window.AppState.parallaxEnabled=!0):(document.body.classList.remove("upgraded-parallax"),window.AppState.parallaxEnabled=!1)}var b=document.querySelectorAll(".image-lazyload");b.forEach(function(a){a.insertAdjacentHTML("afterend",a.textContent);var b=a.previousElementSibling;"IMG"===b.tagName&&b.remove()}),window.addEventListener("resize",a),a()}(),IObserverReady.then(function(){var a=new IntersectionObserver(function(a){a.forEach(function(a){var b=a.target.id;// Remove out-of-screen sections from display
if(.6<=a.intersectionRatio?(a.target.classList.add("active"),document.querySelector("a[href=\"#".concat(b,"\"]")).classList.add("active")):(a.target.classList.remove("active"),document.querySelector("a[href=\"#".concat(b,"\"]")).classList.remove("active")),0==a.intersectionRatio||a.intersectionRatio){var c=document.querySelectorAll("#".concat(b," .hero-image"));c.forEach(function(b){return b.classList.toggle("hide-on-desktop",!a.intersectionRatio)})}})},{root:document.body,threshold:[0,.1,.2,.3,.5,.6,.7,.8,.9,1],rootMargin:"96px 0px 0px 0px"}),b=document.querySelectorAll("section");b.forEach(function(b){return a.observe(b)});var c=document.querySelectorAll("nav a");c.forEach(function(a){return a.classList.add("upgraded")})}),function(){var a=document.querySelector("header");document.body.addEventListener("scroll",function(){32<document.body.scrollTop?a.classList.add("shadow"):a.classList.remove("shadow")},{passive:!0}),a.classList.add("waterfall")},function(){var a=document.querySelector("#nav-toggle");a.addEventListener("change",function(){var b=function(c){c.target.closest("nav")||c.target.closest("label[for=\"nav-toggle\"]")||(a.checked=!1,window.removeEventListener("click",b,{passive:!0}))};a.checked?window.addEventListener("click",b,{passive:!0}):window.removeEventListener("click",b,{passive:!0})})}(),function(){window.onpopstate=function(){// Check state for open overlays and if there is one, close it
if(window.AppState.openedOverlay){var a=window.AppState.openedOverlay;// App is structured so clicking this element should close the overlay
window.AppState.openedOverlay=null,a.click()}}}(),function(){function a(){var a=document.createElement("script");a.setAttribute("src","js/phone-parallax.js"),a.setAttribute("defer",!0),document.head.appendChild(a)}PARALLAX_SUPPORTED&&"DeviceOrientationEvent"in window&&(window.matchMedia(DESKTOP_MQ).matches?window.addEventListener("resize",function b(){window.matchMedia(DESKTOP_MQ).matches||(IObserverReady.then(function(){return a()}),window.removeEventListener("resize",b))}):IObserverReady.then(function(){return a()}))}();